CVProject-master/Controllers/CVController.cs
using CVProject.Models.Repository;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using CVProject.Models.Repository.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using static System.Net.Mime.MediaTypeNames;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Numerics;

namespace CVProject.Controllers
{
    public class CVController : Controller
    {
        private readonly List<string> _validImageFormats = [".png", ".jpeg", ".jpg"];
        private readonly CvContext _context;
        private UserManager<Profile> _userManager;

        public CVController(CvContext context, UserManager<Profile> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ShowCV()
        {
            try
            {
                var cvViewModelList = new List<CVViewModel>();

                var profil = await _userManager.GetUserAsync(User);

                var cv = _context.CVs
                    .AsNoTracking()
                    .Include(c => c.Profil)
                    .Include(c => c.Image)
                    .Where(c => c.AnvandarNamn == profil.Id)
                    .OrderByDescending(c => c.CreatedDate)
                    .ToList();

                foreach (var cV in cv)
                {
                    var cvViewModel = new CVViewModel();
                    cvViewModel.CV = cV;

                    var projects = _context.CVProject
                    .Where(cp => cp.Cvid == cV.Id)
                    .Select(pp => pp.Project)
                    .ToList();

                    cvViewModel.Projects.AddRange(projects);

                    cvViewModelList.Add(cvViewModel);
                }

                return View(cvViewModelList);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> ShowSingleCVAndIncrement(CV cv)
        {
            try
            {
                var cvViewModel = new CVViewModel();

                var projects = _context.CVProject
                .Where(cp => cp.Cvid == cv.Id)
                .Select(pp => pp.Project)
                .ToList();

                cvViewModel.Projects.AddRange(projects);

                var updatedCv = await _context.CVs.Where(_ => _.Id == cv.Id)
                    .Include(_ => _.Profil)
                    .Include(_ => _.Image)
                    .FirstOrDefaultAsync();

                updatedCv.Views = (updatedCv.Views != null) ? updatedCv.Views + 1 : 1;

                cvViewModel.CV = updatedCv;

                await _context.SaveChangesAsync();

                return View("CvDetails", cvViewModel);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        public async Task<IActionResult> ShowCVOtherUser(string ID)
        {
            try
            {
                var cvViewModelList = new List<CVViewModel>();

                var profil = await _userManager.FindByIdAsync(ID);

                var cv = _context.CVs
                    .AsNoTracking()
                    .Include(c => c.Profil)
                    .Include(c => c.Image)
                    .Where(c => c.AnvandarNamn == profil.Id)
                    .OrderByDescending(c => c.CreatedDate)
                    .ToList();

                foreach (var cV in cv)
                {
                    var cvViewModel = new CVViewModel();
                    cvViewModel.CV = cV;

                    var projects = _context.CVProject
                    .Where(cp => cp.Cvid == cV.Id)
                    .Select(pp => pp.Project)
                    .ToList();

                    cvViewModel.Projects.AddRange(projects);

                    cvViewModelList.Add(cvViewModel);
                }

                return View(cvViewModelList);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> ShowSimilarCV(string ID)
        {
            try
            {
                var cvViewModelList = new List<CVViewModel>();

                var profil = await _userManager.FindByIdAsync(ID);

                // Hämta de första tre bokstäverna av förnamn och efternamn
                var firstNamePrefix = profil.Fornamn?.Substring(0, Math.Min(3, profil.Fornamn.Length));
                var lastNamePrefix = profil.Efternamn?.Substring(0, Math.Min(3, profil.Efternamn.Length));

                // Hämta CV:en med matchande förnamn eller efternamn (tre första bokstäver)
                var similarCVs = _context.CVs
                    .AsNoTracking()
                    .Include(c => c.Profil)
                    .Include(c => c.Image)
                    .Where(c =>
                        (c.Profil.Fornamn != null && c.Profil.Fornamn.StartsWith(firstNamePrefix)) ||
                        (c.Profil.Efternamn != null && c.Profil.Efternamn.StartsWith(lastNamePrefix)))
                    .OrderByDescending(c => c.CreatedDate)
                    .ToList();

                foreach (var cV in similarCVs)
                {
                    var cvViewModel = new CVViewModel();
                    cvViewModel.CV = cV;

                    var projects = _context.CVProject
                    .Where(cp => cp.Cvid == cV.Id)
                    .Select(pp => pp.Project)
                    .ToList();

                    cvViewModel.Projects.AddRange(projects);

                    cvViewModelList.Add(cvViewModel);
                }

                return View(cvViewModelList);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditCV(int id)
        {
            try
            {
                var existingCV = await _context.CVs
                    .Include(c => c.Image)
                    .FirstOrDefaultAsync(c => c.Id == id);

                var profile = await _userManager.GetUserAsync(User);

                var profileProjects = _context.ProfileProject
                    .Where(pp => pp.Profileid == profile.Id)
                    .Select(pp => pp.Project)
                    .ToList();

                var CVProjects = _context.CVProject
                    .Where(cp => cp.Cvid == id)
                    .Select(pp => pp.Project)
                    .ToList();

                var allProjects = new List<Project>();
                allProjects.AddRange(CVProjects);
                allProjects.AddRange(profileProjects);

                var uniqueProjects = allProjects.DistinctBy(project => project.ProjectID).ToList();

                if (existingCV != null)
                {
                    var cvViewModel = new CVViewModel
                    {
                        CV = existingCV,
                    
                    // Hämtar den deta vi vill visa på redigeringssidan
                    };

                    cvViewModel.Projects.AddRange(uniqueProjects);

                    return View(cvViewModel);
                }

                return NotFound();
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> CreateCV()
        {
            try
            {
                CVViewModel nyModel = new CVViewModel();
                var profile = await _userManager.GetUserAsync(User);
                var profileProjects = _context.ProfileProject
                    .Where(pp => pp.Profileid == profile.Id)
                    .Select(pp => pp.Project)
                    .ToList();

                nyModel.Projects.AddRange(profileProjects);
                return View(nyModel);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public async Task<IActionResult> CreateCV(CVViewModel cvViewModel)
        {
            try
            {
                var profil = await _userManager.GetUserAsync(User) ?? throw new Exception("Could not find user");
                cvViewModel.CV.AnvandarNamn = profil.Id;

                var imageFile = cvViewModel.ImageFile;
                cvViewModel.CV.Views = 0;

                //Skapar en bild on den finns
                if (IsValidImageFormat(imageFile?.FileName) && imageFile?.Length > 0)
                {
                    var image = CreateImage(imageFile);
                    cvViewModel.CV.Image = image;
                }

                _context.CVs.Add(cvViewModel.CV);
                await _context.SaveChangesAsync();

                foreach (var projectID in cvViewModel.SelectedProjectIds)
                {
                    var cvProject = new CV_Project();
                    cvProject.Cvid = cvViewModel.CV.Id;
                    cvProject.Projectid = projectID;
                    _context.CVProject.Add(cvProject);
                }
                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

CVProject-master/Controllers/MessageController.cs
using CVProject.Models.Repository;
using CVProject.Models.Repository.Entity;
using CVProject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CVProject.Controllers
{
    public class MessageController : Controller
    {
        private readonly CvContext _context;
        private UserManager<Profile> _userManager;

        public MessageController(CvContext context, UserManager<Profile> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Inbox()
        {
            try
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var messages = await _context.Messages
                    .AsNoTracking()
                    .Include(_ => _.avsandare)
                    .Where(_ => _.mottagare.Id == user.Id.ToString())
                    .ToListAsync();

                var guestMessages = await _context.GuestMessages.Where(_ => _.mottagare.Id == user.Id.ToString()).ToListAsync();

                var viewModel = new MessageGuestMessageViewModel
                {
                    Messages = messages,
                    GuestMessages = guestMessages
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public IActionResult MarkAsRead(int messageId)
        {
            try
            {
                var meddelandet = _context.Messages.Find(messageId);

                var guesstMeddelandet = _context.GuestMessages.Find(messageId);

                if (meddelandet != null && meddelandet.LasDatum == false)
                {
                    meddelandet.LasDatum = true;
                }
                else if (meddelandet != null && meddelandet.LasDatum == true)
                {
                    meddelandet.LasDatum = false;
                }

                if (guesstMeddelandet != null && guesstMeddelandet.LasDatum == false)
                {
                    guesstMeddelandet.LasDatum = true;
                }
                else if (guesstMeddelandet != null && guesstMeddelandet.LasDatum == true)
                {
                    guesstMeddelandet.LasDatum = false;
                }

                _context.SaveChanges();

                return RedirectToAction("Inbox");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public IActionResult MarkAsDeleted(int messageId)
        {
            try
            {
                var meddelandet = _context.Messages.Find(messageId);

                var guestMeddelandet = _context.GuestMessages.Find(messageId);
                if (meddelandet != null)
                {
                    meddelandet.ArRaderad = true;
                }
                if (guestMeddelandet != null)
                {
                    guestMeddelandet.ArRaderad = true;
                }
                _context.SaveChanges();
                return RedirectToAction("Inbox");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(MessageProfileViewModel viewModel, string id)
        {
            try
            {
                var profil = await _userManager.GetUserAsync(User);
                if (profil == null)
                {
                    if (ModelState.IsValid)
                    {
                        var message = new GuestMessage
                        {
                            Innehall = viewModel.Innehall,
                            Datum = DateTime.Now,
                            LasDatum = false,
                            Avsandare = viewModel.Avsandare,
                            Mottagare = id
                        };

                        _context.GuestMessages.Add(message);

                        await _context.SaveChangesAsync();
                    }
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        var message = new Message
                        {
                            Innehall = viewModel.Innehall,
                            Datum = DateTime.Now,
                            LasDatum = false,
                            Avsandare = profil.Id,
                            Mottagare = id
                        };
                        _context.Messages.Add(message);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }
    }
}

CVProject-master/Views/Home/LoggedInStart.cshtml
@model CVProject.Models.Repository.Entity.All_CV_Project

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div class="container mt-5">
        <h2 class="display-4">Välkommen @User.Identity.Name</h2>
        <div class="row">
            @if (Model.Project != null @* && Model.Project.Any() *@)
            {
                    <div class="col-md-4 mb-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h5 class="card-title">@Model.Project.Title</h5>
                                <p class="card-text">@Model.Project.Description</p>
                                <p class="card-text">@Model.Project.DatumProjekt</p>
                                <a href="@Url.Action("ShowProject", "Project")" class="btn btn-primary btn-block">Visa Projekt</a>
                            </div>
                        </div>
                    </div>
            }
        </div>
        <div class="row">
            @foreach (var cv in Model.CVs)
            {
            <div class="col-md-4 mb-4">
                <div class="card mb-4" style="height: 400px; position: relative; overflow: hidden;">
                @if (cv.Image != null)
                {
                    var base64 = Convert.ToBase64String(cv.Image.Image!);
                    var imgSrc = $"data:image/gif;base64,{base64}";
                    <img src="@imgSrc" class="card-img-top img-fluid rounded-circle" alt="Profilbild" style="height: 150px; width: 150px; margin-top: 10px; margin-left: 10px;" />

                    <div class="card-body" style="position: absolute; bottom: 0; left: 0; width: 100%;">
                        <h5 class="card-title">@cv.Profil.Fornamn @cv.Profil.Efternamn</h5>
                        <p class="card-text">Kompetenser: @cv.Kompetenser</p>
                        <p class="card-text">Utbildningar: @cv.Utbildningar</p>
                        @using (Html.BeginForm("ShowSingleCVAndIncrement", "CV", cv, FormMethod.Post))
                        {
                                <button type="submit" class="btn btn-primary btn-block"  style="width: 60%">
                                    Visa CV
                                </button>
                        }
                    </div>
                }
                else
                {
                    
                    <i class="fas fa-user fa-5x text-secondary" style="height: 150px; width: 150px; margin-top: 40px; margin-left: 40px;"></i>

                    <div class="card-body" style="position: absolute; bottom: 0; left: 0; width: 100%;">
                        <h5 class="card-title">@cv.Profil.Fornamn @cv.Profil.Efternamn</h5>
                        <p class="card-text">Kompetenser: @cv.Kompetenser</p>
                        <p class="card-text">Utbildningar: @cv.Utbildningar</p>
                        @using (Html.BeginForm("ShowSingleCVAndIncrement", "CV", cv, FormMethod.Post))
                        {
                                <button type="submit" class="btn btn-primary btn-block"  style="width: 60%">
                                    Visa CV
                                </button>
                        }
                    </div>
                }
                </div>
            </div>

            }
        </div>
    </div>

   
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"</script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"</script>
</body>
</html>

CVProject-master/Views/Home/LoggedOutStart.cshtml
@model CVProject.Models.Repository.Entity.All_CV_Project

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- FontAwesome för ikoner -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div class="container mt-5">
        <h2 class="display-4">Välkommen</h2>

        <div class="row">
            @foreach (var cv in Model.CVs)
            {
                <div class="col-md-4 mb-4">
                    <div class="card mb-4" style="height: 400px; position: relative; overflow: hidden;">
                @if (cv.Image != null)
                {
                    var base64 = Convert.ToBase64String(cv.Image.Image!);
                    var imgSrc = $"data:image/gif;base64,{base64}";
                    <img src="@imgSrc" class="card-img-top img-fluid rounded-circle" alt="Profilbild" style="height: 150px; width: 150px; margin-top: 10px; margin-left: 10px;" />

                    <div class="card-body" style="position: absolute; bottom: 0; left: 0; width: 100%;">
                        <h5 class="card-title">@cv.Profil.Fornamn @cv.Profil.Efternamn</h5>
                        <p class="card-text">Kompetenser: @cv.Kompetenser</p>
                        <p class="card-text">Utbildningar: @cv.Utbildningar</p>
                        @using (Html.BeginForm("ShowSingleCVAndIncrement", "CV", cv, FormMethod.Post))
                        {
                            <button type="submit" class="btn btn-primary btn-block"  style="width: 60%">
                                Visa CV
                            </button>
                        }
                    </div>
                }
                else
                {
                   
                    <i class="fas fa-user fa-5x text-secondary" style="height: 150px; width: 150px; margin-top: 40px; margin-left: 40px;"></i>

                    <div class="card-body" style="position: absolute; bottom: 0; left: 0; width: 100%;">
                        <h5 class="card-title">@cv.Profil.Fornamn @cv.Profil.Efternamn</h5>
                        <p class="card-text">Kompetenser: @cv.Kompetenser</p>
                        <p class="card-text">Utbildningar: @cv.Utbildningar</p>
                        @using (Html.BeginForm("ShowSingleCVAndIncrement", "CV", cv, FormMethod.Post))
                        {
                                <button type="submit" class="btn btn-primary btn-block"  style="width: 60%">
                                    Visa CV
                                </button>
                        }
                    </div>
                }
            </div>
        </div>
            }
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.3/umd/popper.min.js"</script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"</script>
</body>
</html>

CVProject-master/Views/Home/Search.cshtml
@using CVProject.Models.ViewModels
@model List<SearchResultViewModel>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
     <div>
    @{
        if (Model == null || Model.Count < 1)
        {
            <h2>Hittade inga profiler</h2>
        }
        else
        {
            <h2>Sökresultat</h2>
            foreach (var result in Model)
            {
                if (result.Profil.Image != null)
                {
                    var base64 = Convert.ToBase64String(result.Profil.Image.Image!);
                    var imgSrc = $"data:image/gif;base64,{base64}";
                    <img src="@imgSrc" alt="Profilbild" />
                }
                else
                {
                    <p>Ingen profilbild tillgänglig.</p>
                }
                <div>
                    <label>Användarnamn: @result.Profil.Anvandarnamn</label>
                </div>
                <div>
                    <label>Namn: @result.Profil.Fornamn @result.Profil.Efternamn</label>
                </div>
                <div>
                    <label>Email: @result.Profil.Email</label>
                </div>
                <br/>
                <div>
                    @{
                        foreach(var cv in result.CV)
                        {
                            <label>Kompetens: @cv.Kompetenser</label>
                        }
                    }
                </div>
                <br />
                <button>
                    <a asp-controller="Message" asp-action="SendMessage" asp-route-id="@result.Profil.Id" asp-route-username="@result.Profil.Anvandarnamn">Skicka meddelande här</a>
                </button>
                <br/>
                <br/>
            }
        }
    }
    </div>