CVProject-master/Controllers/MessageController.cs
using CVProject.Models.Repository;
using CVProject.Models.Repository.Entity;
using CVProject.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CVProject.Controllers
{
    public class MessageController : Controller
    {
        private readonly CvContext _context;
        private UserManager<Profile> _userManager;

        public MessageController(CvContext context, UserManager<Profile> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Inbox()
        {
            try
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                var messages = await _context.Messages
                    .AsNoTracking()
                    .Include(_ => _.avsandare)
                    .Where(_ => _.mottagare.Id == user.Id.ToString())
                    .ToListAsync();

                var guestMessages = await _context.GuestMessages.Where(_ => _.mottagare.Id == user.Id.ToString()).ToListAsync();

                var viewModel = new MessageGuestMessageViewModel
                {
                    Messages = messages,
                    GuestMessages = guestMessages
                };

                return View(viewModel);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public IActionResult MarkAsRead(int messageId)
        {
            try
            {
                var meddelandet = _context.Messages.Find(messageId);

                var guesstMeddelandet = _context.GuestMessages.Find(messageId);

                if (meddelandet != null && meddelandet.LasDatum == false)
                {
                    meddelandet.LasDatum = true;
                }
                else if (meddelandet != null && meddelandet.LasDatum == true)
                {
                    meddelandet.LasDatum = false;
                }

                if (guesstMeddelandet != null && guesstMeddelandet.LasDatum == false)
                {
                    guesstMeddelandet.LasDatum = true;
                }
                else if (guesstMeddelandet != null && guesstMeddelandet.LasDatum == true)
                {
                    guesstMeddelandet.LasDatum = false;
                }

                _context.SaveChanges();

                return RedirectToAction("Inbox");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public IActionResult MarkAsDeleted(int messageId)
        {
            try
            {
                var meddelandet = _context.Messages.Find(messageId);

                var guestMeddelandet = _context.GuestMessages.Find(messageId);
                if (meddelandet != null)
                {
                    meddelandet.ArRaderad = true;
                }
                if (guestMeddelandet != null)
                {
                    guestMeddelandet.ArRaderad = true;
                }
                _context.SaveChanges();
                return RedirectToAction("Inbox");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendMessage(MessageProfileViewModel viewModel, string id)
        {
            try
            {
                var profil = await _userManager.GetUserAsync(User);
                if (profil == null)
                {
                    if (ModelState.IsValid)
                    {
                        var message = new GuestMessage
                        {
                            Innehall = viewModel.Innehall,
                            Datum = DateTime.Now,
                            LasDatum = false,
                            Avsandare = viewModel.Avsandare,
                            Mottagare = id
                        };

                        _context.GuestMessages.Add(message);

                        await _context.SaveChangesAsync();
                    }
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        var message = new Message
                        {
                            Innehall = viewModel.Innehall,
                            Datum = DateTime.Now,
                            LasDatum = false,
                            Avsandare = profil.Id,
                            Mottagare = id
                        };
                        _context.Messages.Add(message);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }
    }
}

CVProject-master/Controllers/ProfileController.cs
using CVProject.Models.Repository;
using CVProject.Models.Repository.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CVProject.Controllers
{
    public class ProfileController : Controller
    {
        private readonly List<string> _validImageFormats = [".png", ".jpeg", ".jpg"];
        private readonly CvContext _context;
        private UserManager<Profile> userManager;
        private SignInManager<Profile> signInManager;

        public ProfileController(CvContext context, UserManager<Profile> userMgr, SignInManager<Profile> signInmag)
        {
            _context = context;
            this.userManager = userMgr;
            this.signInManager = signInmag;
        }

        [HttpGet]
        public async Task<IActionResult> ShowProfile()
        {
            try
            {
                var profil = await userManager.GetUserAsync(User);
                var profileWithImage = _context.Profiles
                    .AsNoTracking()
                    .Include(c => c.Image)
                    .Where(c => c.Anvandarnamn == profil.Anvandarnamn)
                    .FirstOrDefault();

                return View(profileWithImage);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> ShowProfileOtherUser(string ID)
        {
            try
            {
                var profil = await userManager.FindByIdAsync(ID);
                return View(profil);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public IActionResult LogInUser()
        {
            try
            {
                Profile Loggprofil = new Profile();
                return View(Loggprofil);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }
        public IActionResult RegisterUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LogInUser(Profile Loggprofil)
        {
            try
            {
                if (string.IsNullOrEmpty(Loggprofil.Anvandarnamn) || string.IsNullOrEmpty(Loggprofil.Losenord))
                {
                    TempData["FelMeddelande"] = "Fel användarnamn eller lösenord.";
                    return View(Loggprofil);
                }


                var resultat = await signInManager.PasswordSignInAsync(
                Loggprofil.Anvandarnamn,
                Loggprofil.Losenord,
                isPersistent: false,
                lockoutOnFailure: false
                );

                if (resultat.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                TempData["FelMeddelande"] = "Fel användarnamn eller lösenord.";
                return View(Loggprofil);
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Register(Profile profil, IFormFile imageFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    profil.UserName = profil.Anvandarnamn;
                    profil.PasswordHash = userManager.PasswordHasher.HashPassword(profil, profil.Losenord);

                    ////Skapar en bild on den finns
                    if (IsValidImageFormat(imageFile?.FileName) && imageFile?.Length > 0)
                    {
                        var image = CreateImage(imageFile);
                        profil.Image = image;
                    }
                    await userManager.CreateAsync(profil);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View("RegisterUser");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> EditProfile()
        {
            var profil = await userManager.GetUserAsync(User);
            return View(profil);
        }

        public async Task<IActionResult> Update(string fornamn, string efternamn, string losenord, string email, string phonenumber, string adress, bool? privat)
        {
            try
            {
                var profil = await userManager.GetUserAsync(User);

                if (profil != null)
                {
                    if (!string.IsNullOrEmpty(fornamn))
                    {
                        profil.Fornamn = fornamn;
                    }

                    if (!string.IsNullOrEmpty(efternamn))
                    {
                        profil.Efternamn = efternamn;
                    }

                    if (!string.IsNullOrEmpty(losenord))
                    {
                        profil.Losenord = losenord;
                    }

                    if (!string.IsNullOrEmpty(email))
                    {
                        profil.Email = email;
                    }

                    if (!string.IsNullOrEmpty(phonenumber))
                    {
                        profil.PhoneNumber = phonenumber;
                    }

                    if (!string.IsNullOrEmpty(adress))
                    {
                        profil.Adress = adress;
                    }

                    if (privat.HasValue)
                    {
                        profil.Privat = privat.Value;
                    }

                    profil.PasswordHash = userManager.PasswordHasher.HashPassword(profil, profil.Losenord);
                    _context.Profiles.Update(profil);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction("ShowProfile");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }


        [HttpPost]
        public async Task<IActionResult> InactivateAccount()
        {
            try
            {
                var profil = await userManager.GetUserAsync(User);
                profil.ArInaktiverad = true;
                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                Console.WriteLine($"Error: {e.Message}");
                return RedirectToAction("Error");
            }
        }

        private bool IsValidImageFormat(string? fileName)
        {
            if (fileName == null) return false;
            foreach (var format in _validImageFormats)
            {
                if (fileName.EndsWith(format, StringComparison.InvariantCultureIgnoreCase)) return true;
            }

            return false;
        }

        private Images CreateImage(IFormFile file)
        {
            var image = new Images();
            using (var ms = new MemoryStream())
            {
                file.CopyTo(ms);
                image.Image = ms.ToArray();
            }
            image.FileName = file.FileName;
            image.FileType = file.FileName[(file.FileName.LastIndexOf('.') + 1)..].ToUpper();

            return image;
        }
    }
}

CVProject-master/ViewCompopents/UnreadMessagesViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CVProject.Models.Repository;
using CVProject.Models.Repository.Entity;
using Microsoft.AspNetCore.Identity;

public class UnreadMessagesViewComponent : ViewComponent
{
    private readonly CvContext _context;
    private readonly UserManager<Profile> _userManager;

    public UnreadMessagesViewComponent(CvContext context, UserManager<Profile> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var user = await _userManager.GetUserAsync(HttpContext.User);

        if (user != null)
        {
            // Räkna olästa meddelanden från aktiva användare
            var unreadMessagesCount = await _context.Messages.CountAsync(m => m.mottagare.Id == user.Id && !m.LasDatum && m.ArRaderad == false && m.avsandare.ArInaktiverad == false);

            // Räkna olästa gästmeddelanden
            var guessUnreadMessagesCount = await _context.GuestMessages.CountAsync(m => m.mottagare.Id == user.Id && !m.LasDatum && m.ArRaderad == false);

            // Skickar datan till vyn
            ViewBag.UnreadMessagesCount = unreadMessagesCount + guessUnreadMessagesCount;
        }
        return View();
    }



}

CVProject-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CVProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CVProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fas fa-home"></i> Start</a>
                        </li>
                        <!-- Add the new icon link to your page here -->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="ShowProject"><i class="fas fa-cubes"></i> Projekt</a>
                        </li>
                        @if (User?.Identity != null && User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="ShowProfile"><i class="fas fa-user"></i> Profil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Inbox"><i class="fas fa-inbox"></i> Inbox @await Component.InvokeAsync("UnreadMessages")</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#" onclick="document.getElementById('logoutForm').submit();"><i class="fas fa-sign-out-alt"></i> Logga ut</a>
                            </li>
                            <form id="logoutForm" method="post" asp-controller="Profile" asp-action="Logout"></form>
                        }
                        else
                        {
                                <!-- Om användaren inte är inloggad -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="RegisterUser"><i class="fas fa-user-plus"></i> Ny användare</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile" asp-action="LogInUser"><i class="fas fa-sign-in-alt"></i> Logga in</a>
                            </li>
                        }
                    </ul>

                    <!-- Sökfält och knapp -->
                    <form class="form-inline my-2 my-lg-0" asp-controller="Home" asp-action="Search" method="get">
                        <div class="input-group">
                            <input class="form-control rounded mr-sm-2" type="text" placeholder="Sök profil" name="profileName" />
                            <div class="input-group-append">
                                <button class="btn btn-outline-success ml-2" type="submit" style="margin-left: 8px;"><i class="fas fa-search"></i> Sök</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer -->
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>